### PR TITLE
Fix UDP read function

### LINKED ISSUE #32: UDPInterface::read doesn't work
The packet always comes back with empty data of size 0.

After reading some of the asio docs and examples, I'm fairly certain that the `socket.available()` function doesn't work for blocking reads. From the [docs](https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/basic_datagram_socket/available/overload1.html):

> The number of bytes that may be read without blocking, or 0 if an error occurs.

I think the `available()` function is meant for async operations, which is not what is employed by the existing library.

Change to a set buffer size that is configurable during opening the socket.

### PR DESCRIPTION
**Pull request by icolwell-as**
Resolves #32, see issue for more details.

### CODE REVIEW

**Review by dvangeyn-as — APPROVED** [review]

**Review by shan-as — APPROVED** [review]

File: include/network_interface/network_interface.h [hunk 1]
```diff
@@ -50,6 +51,7 @@ class UDPInterface
   ReturnStatuses write(const std::vector<uint8_t>& msg);
 
 private:
+  uint receive_buffer_size_ = 1024;
```
Comment (jilinzhou) [inline include/network_interface/network_interface.h:54]: uint32_t

File: src/udp_interface.cpp [hunk 2]
```diff
@@ -19,6 +19,12 @@ UDPInterface::UDPInterface() :
 {
 }
 
+ReturnStatuses UDPInterface::open(std::string ip_address, const int &port, uint receive_buffer_size)
```
Comment (jilinzhou) [inline src/udp_interface.cpp:22]: uint32_t

File: src/udp_interface.cpp [hunk 3]
```diff
@@ -19,6 +19,12 @@ UDPInterface::UDPInterface() :
...
+{
+  receive_buffer_size_ = receive_buffer_size;
+  return UDPInterface::open(ip_address, port);
+}
+
 ReturnStatuses UDPInterface::open(std::string ip_address, const int &port)
```
Comment (jilinzhou) [inline src/udp_interface.cpp:28]: should be (const std::string& ip_address, int port)
